// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4BFbbK-Se-YLw1M2lWZyZdj7Hem3XIU',
    appId: '1:1065942806413:web:9b3cb7aef65decafec17c4',
    messagingSenderId: '1065942806413',
    projectId: 'fleet-management-db',
    authDomain: 'fleet-management-db.firebaseapp.com',
    storageBucket: 'fleet-management-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8FEPXI9bSwGWyTPEC_jsZg_aORs8mmhI',
    appId: '1:1065942806413:android:11a5860842e137efec17c4',
    messagingSenderId: '1065942806413',
    projectId: 'fleet-management-db',
    storageBucket: 'fleet-management-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzVWF3eeEkvSCkfTsE0YKxZe7Z9b9cC0',
    appId: '1:1065942806413:ios:59c4657d305a92efec17c4',
    messagingSenderId: '1065942806413',
    projectId: 'fleet-management-db',
    storageBucket: 'fleet-management-db.firebasestorage.app',
    iosBundleId: 'com.example.fleetManagement',
  );

}